name: Keep Supabase Awake

on:
  schedule:
    - cron: '0 0 * * 0,2,4' # Runs automatically every Sun, Tue, Thu
  workflow_dispatch: # Allows manual testing

jobs:
  ping_db:
    runs-on: ubuntu-latest
    steps:
      - name: Send API Request
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X GET "https://supabase.co" \
          -H "apikey: sb_publishable_FTiUYQt0XB7d7BcsGKesDA_ERo2G-lz" \
          -H "Authorization: Bearer sb_publishable_FTiUYQt0XB7d7BcsGKesDA_ERo2G-lz" \
          -H "Content-Profile: public")
          
          echo "Status: $RESPONSE"
